#!/bin/bash

# ============================================
# HEPHAITOS Performance Monitor (2026)
# ============================================

set -e

echo "📊 HEPHAITOS Performance Monitor"
echo "================================="

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
THRESHOLD_BUILD_TIME=120  # seconds
THRESHOLD_BUNDLE_SIZE=500 # KB
THRESHOLD_LIGHTHOUSE=85   # score

# Function: Measure build time
measure_build_time() {
  echo -e "\n${YELLOW}⏱️ Measuring build time...${NC}"

  START_TIME=$(date +%s)
  npm run build > /dev/null 2>&1
  END_TIME=$(date +%s)

  BUILD_TIME=$((END_TIME - START_TIME))

  echo "Build time: ${BUILD_TIME}s"

  if [ $BUILD_TIME -gt $THRESHOLD_BUILD_TIME ]; then
    echo -e "${RED}⚠️ Build time exceeds threshold (${THRESHOLD_BUILD_TIME}s)${NC}"
    return 1
  else
    echo -e "${GREEN}✅ Build time OK${NC}"
    return 0
  fi
}

# Function: Analyze bundle size
analyze_bundle_size() {
  echo -e "\n${YELLOW}📦 Analyzing bundle size...${NC}"

  # Get main bundle size
  BUNDLE_SIZE=$(du -sk .next/static/chunks/main-*.js 2>/dev/null | cut -f1 || echo "0")

  echo "Main bundle: ${BUNDLE_SIZE}KB"

  if [ $BUNDLE_SIZE -gt $THRESHOLD_BUNDLE_SIZE ]; then
    echo -e "${RED}⚠️ Bundle size exceeds threshold (${THRESHOLD_BUNDLE_SIZE}KB)${NC}"
    return 1
  else
    echo -e "${GREEN}✅ Bundle size OK${NC}"
    return 0
  fi
}

# Function: Run Lighthouse audit
run_lighthouse() {
  echo -e "\n${YELLOW}🏠 Running Lighthouse audit...${NC}"

  # Start dev server
  npm run dev > /dev/null 2>&1 &
  DEV_PID=$!
  sleep 10

  # Run Lighthouse
  npx lighthouse http://localhost:3000 \
    --output json \
    --output-path ./lighthouse-report.json \
    --quiet

  # Kill dev server
  kill $DEV_PID

  # Parse score
  PERFORMANCE_SCORE=$(jq -r '.categories.performance.score * 100' lighthouse-report.json 2>/dev/null || echo "0")

  echo "Performance score: ${PERFORMANCE_SCORE}"

  if [ $(echo "$PERFORMANCE_SCORE < $THRESHOLD_LIGHTHOUSE" | bc) -eq 1 ]; then
    echo -e "${RED}⚠️ Performance score below threshold (${THRESHOLD_LIGHTHOUSE})${NC}"
    return 1
  else
    echo -e "${GREEN}✅ Performance score OK${NC}"
    return 0
  fi
}

# Function: Check memory usage
check_memory_usage() {
  echo -e "\n${YELLOW}💾 Checking memory usage...${NC}"

  # Run build and capture memory
  NODE_OPTIONS="--max-old-space-size=2048" npm run build 2>&1 | tee build.log

  # Check for OOM
  if grep -q "heap out of memory" build.log; then
    echo -e "${RED}❌ Out of memory error detected${NC}"
    rm build.log
    return 1
  else
    echo -e "${GREEN}✅ Memory usage OK${NC}"
    rm build.log
    return 0
  fi
}

# Function: Generate performance report
generate_report() {
  echo -e "\n${YELLOW}📝 Generating performance report...${NC}"

  REPORT_FILE="performance-report-$(date +%Y%m%d-%H%M%S).md"

  cat > $REPORT_FILE <<EOF
# HEPHAITOS Performance Report

**Generated**: $(date)

## Metrics

| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| Build Time | ${BUILD_TIME}s | ${THRESHOLD_BUILD_TIME}s | $([ $BUILD_TIME -le $THRESHOLD_BUILD_TIME ] && echo "✅ PASS" || echo "❌ FAIL") |
| Bundle Size | ${BUNDLE_SIZE}KB | ${THRESHOLD_BUNDLE_SIZE}KB | $([ $BUNDLE_SIZE -le $THRESHOLD_BUNDLE_SIZE ] && echo "✅ PASS" || echo "❌ FAIL") |
| Lighthouse | ${PERFORMANCE_SCORE} | ${THRESHOLD_LIGHTHOUSE} | $([ $(echo "$PERFORMANCE_SCORE >= $THRESHOLD_LIGHTHOUSE" | bc) -eq 1 ] && echo "✅ PASS" || echo "❌ FAIL") |

## Recommendations

$([ $BUILD_TIME -gt $THRESHOLD_BUILD_TIME ] && echo "- ⚠️ Optimize build process (consider caching)" || echo "- ✅ Build time is optimal")
$([ $BUNDLE_SIZE -gt $THRESHOLD_BUNDLE_SIZE ] && echo "- ⚠️ Reduce bundle size (code splitting, tree shaking)" || echo "- ✅ Bundle size is optimal")
$([ $(echo "$PERFORMANCE_SCORE < $THRESHOLD_LIGHTHOUSE" | bc) -eq 1 ] && echo "- ⚠️ Improve Lighthouse score (lazy loading, compression)" || echo "- ✅ Performance score is optimal")

---
*Auto-generated by HEPHAITOS Performance Monitor*
EOF

  echo -e "${GREEN}✅ Report saved: $REPORT_FILE${NC}"
}

# Main execution
main() {
  FAILED=0

  measure_build_time || FAILED=$((FAILED + 1))
  analyze_bundle_size || FAILED=$((FAILED + 1))
  check_memory_usage || FAILED=$((FAILED + 1))

  # Optional: Lighthouse (commented out for speed)
  # run_lighthouse || FAILED=$((FAILED + 1))

  generate_report

  echo -e "\n================================="
  if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}🎉 All performance checks passed!${NC}"
    exit 0
  else
    echo -e "${RED}⚠️ $FAILED performance check(s) failed${NC}"
    exit 1
  fi
}

# Run main
main
